# Generated by Django 4.1.5 on 2023-01-14 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('UNSET', '---'), ('COMMUNITY', 'まちづくり'), ('DIRECTION', 'ダイレクション'), ('DESIGN', 'デザイン'), ('DTP', 'DTP'), ('CODING', 'コーディング'), ('WEB', 'WEB制作'), ('SUPPORT', '月々サポート'), ('INTERNAL', '社内'), ('OTHER', '他')], default='UNSET', max_length=64, verbose_name='タスク種')),
                ('content', models.TextField(blank=True, default='', verbose_name='備考')),
                ('task_status', models.CharField(choices=[('NOT_STARTED', '未開始'), ('IN_PROGRESS', '作業中'), ('COMPLETE', '完了'), ('WAIT_EXTERNAL', '社外対応待ち'), ('WAIT_INTERNAL', '社内対応待ち'), ('ON_HOLD', '一時停止'), ('CANCEL', '中止'), ('FAIL', '失敗')], default='NOT_STARTED', max_length=64, verbose_name='ステタス')),
                ('deadline', models.DateTimeField(blank=True, verbose_name='期限')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='projects.project', verbose_name='関連プロジェクト')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('voters', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
